#!/bin/sh
#
#    bl-gvim: a wrapper script to invoke gvim in GUI mode.
#    Copyright: 2015 Craig Oakes <bunsen@craigoakes.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Wrapper script to invoke gvim in GUI mode, typically used as target of a
#  link (like /etc/alternatives/bl-text-editor).  Rationale: only links to
#  /usr/bin/vim.* starting with the letter 'g' like /etc/alternatives/gvim or
#  gnome-text-editor actually invoke GUI mode (without using the -g option).

GVIM="`readlink -e /etc/alternatives/gvim`"
SELF=`readlink -f $0`
case $GVIM in
"")
    ERROR="gvim is missing or not installed."
    RX="Install vim-gnome, vim-gtk, or vim-athena."
    if [ "$DISPLAY" ] ; then
        TEXT="<big>$ERROR</big>\n\n$RX"
        yad --image=dialog-info --button=OK --title="${SELF##*/}" --text="$TEXT" --width=400 --borders=20 --center
    else
        echo "${SELF##*/}: $ERROR" >&2
    fi
    exit 1
    ;;
"$SELF")
    echo "${SELF##*/}: error attempting to recursively execute self." >&2
    exit 1
    ;;
*)
    gvim "$@"
    ;;
esac

