#!/bin/sh
#  Wrapper script to invoke gvim in GUI mode, typically used as target of a
#  link (like /etc/alternatives/bl-text-editor).  Rationale: only links to
#  /usr/bin/vim.* starting with the letter 'g' like /etc/alternatives/gvim or
#  gnome-text-editor actually invoke GUI mode (without using the -g option).

GVIM="`readlink -e /etc/alternatives/gvim`"
SELF=`readlink -f $0`
case $GVIM in
"")
    ERROR="gvim is missing or not installed."
    RX="Install vim-gnome, vim-gtk, or vim-athena."
    if [ "$DISPLAY" ] ; then
        TEXT="<big>$ERROR</big>\n\n$RX"
        yad --image=dialog-info --button=OK --title="${SELF##*/}" --text="$TEXT" --width=400 --borders=20 --center
    else
        echo "${SELF##*/}: $ERROR" >&2
    fi
    exit 1
    ;;
"$SELF")
    echo "${SELF##*/}: error attempting to recursively execute self." >&2
    exit 1
    ;;
*)
    gvim "$@"
    ;;
esac

