#!/bin/bash

# wrapper for mpv to enable use as alternative for bl-media-player

MPV_PROFILE=pseudo-gui

if ! hash mpv; then
    echo "$0: mpv binary is missing. Please issue 'sudo apt-get install mpv'." >&2
    exit 1
fi

if (( $# > 0 )); then
    FILE=$1

    # Use the MIME type of the first file passed to us to determine the
    # playback profile.
    if [[ -s "$FILE" && "$(file --mime-type --brief "$FILE")" =~ ^audio/ ]]; then
        MPV_PROFILE=audio-only
    fi
fi

exec mpv --terminal=no --input-terminal=no --profile=$MPV_PROFILE "$@"
