#!/bin/bash
#
#    bl-user-setup: a script to populate a new user's HOME directory
#    using template files from /usr/share/bunsen/skel/
#    Copyright: 2015-2016 John Crawley <john@bunsenlabs.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# USER="$1" USER is exported by lightdm
HOME_DIR=$( getent passwd $USER | cut -d: -f6 )
USR_GRP="$( id -ng $USER )"
[ -f "$HOME_DIR/.config/bunsen/bl-setup" ] && exit 0

bkp_sfx="~$( date +%FT%T )~"

rsync -rltb --suffix="$bkp_sfx" --safe-links /usr/share/bunsen/skel/ "$HOME_DIR/"

for i in "$HOME_DIR/.gtk-bookmarks" "/$HOME_DIR/.config/nitrogen/nitrogen.cfg"
do
    [ -f "${i}.template" ] || continue
    sed --in-place "s/%USERNAME%/$USER/g" "${i}.template"
    if [ -f "$i" ]
    then
        if diff -BEbZ "$i" "${i}.template" >/dev/null
        then
            rm "${i}.template"
        else
            mv "$i" "${i}${bkp_sfx}"
            mv "${i}.template" "$i"
        fi
    else
        mv "${i}.template" "$i"
    fi
done

ln -sTf /usr/share/images/bunsen/wallpapers "$HOME_DIR/Pictures/wallpapers/bunsen"

mkdir -p "$HOME_DIR/.config/bunsen" # this should already exist
touch "$HOME_DIR/.config/bunsen/bl-setup"

 chown -R "$USER":"$USR_GRP" "$HOME_DIR"

exit
