#!/bin/bash
# BunsenLabs User Set-up

# USER="$1" USER is exported by lightdm

[ -f "/home/$USER/.config/bunsen/bl-setup" ] && exit 0

cd /usr/share/bunsen/skel
tar cpzf skel.tar.gz .
mv skel.tar.gz /home/$USER/skel.tar.gz
cd /home/$USER
tar --suffix="~$( date +%FT%T )~" -xpsf skel.tar.gz
rm skel.tar.gz

for i in "/home/$USER/.gtk-bookmarks" "/home/$USER/.config/nitrogen/nitrogen.cfg"
do
    [ -f "$i" ] && {
        sed --in-place="~$( date +%FT%T )~" "s/REPLACEME/$USER/g" "$i"
    }
done

ln -s /usr/share/backgrounds "/home/$USER/Pictures/wallpapers/shared"

mkdir -p "/home/$USER/.config/bunsen" # this should already exist
touch "/home/$USER/.config/bunsen/bl-setup"
chown -R "$USER":"$USER" "/home/$USER"

exit
