#!/bin/sh

gtktheme () {
	while IFS='=' read -r key value; do
		key=${key#"${key%%[![:blank:]]*}"} # strip any leading spaces
		key=${key%"${key##*[![:blank:]]}"} # " " trailing " "
		if [ "${key}" = 'gtk-theme-name' ]; then
			value=${value%%#*} # strip trailing comments
			value=${value#"${value%%[![:blank:]]*}"}
			value=${value%"${value##*[![:blank:]]}"}
			printf '%s' "${value}"
			return 0
		fi
	done < "$HOME/.config/gtk-3.0/settings.ini"
}

old=$(cat ~/.cache/jgmenu/.last-gtktheme)
new=$(gtktheme)

if ! [ "${old}" = "${new}" ]; then
	printf '%b\n' "info: change gtk theme from ${old} to ${new}"
	jgmenu_run gtktheme
fi
